services:
  proxy:
    image: haproxy:2.7.10-alpine
    hostname: proxy
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mynet
  frontend:
    build: .
    hostname: frontend
    networks:
      - mynet
    ports:
      - "3001:3001"
  db:
    build: 
      context: .
      dockerfile: ./Dockerfile-DB
    hostname: db
    networks:
      - mynet
    ports: 
      - "3000:3000"

networks:
  mynet:
    driver: bridge

volumes:
  haproxy: